config/routes.rb
Rails.application.routes.draw do
  
  get 'shoes/:id/send_mail' => 'shoes#send_mail', as: :send_mail

  devise_for :admins
  devise_for :users
  
  resources :comments

  resources :categories

  resources :companies

  resources :shoes
  root to: 'shoes#index'

end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
	validates :name,:description,:price, presence: true
	validates :name, length: {minimum: 5}
	validates :description, length: {maximum: 255}
	validates :price,numericality: true
	#default_scope {order('price DESC')}

	mount_uploader :image, ImageUploader
	belongs_to :category
	belongs_to :company
	is_impressionable counter_cache: true, unique: :all
	acts_as_commentable
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy, :send_mail]
  impressionist :actions=>[:show,:index]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.paginate(:page => params[:page], :per_page => 5).order('price DESC')    
    @most_viewed = Shoe.order('impressions_count DESC').take(3)
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @all_comments = @shoe.comments
    @create_comment = @shoe.comments.build
  end

  def send_mail
    @all_comments = @shoe.comments
    @email = params[:email]
    ShoeMailer.shoe_info(@email,@shoe,@all_comments).deliver
    redirect_to shoe_path(@shoe)
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:name, :description, :price, :image, :category_id, :company_id)
    end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/shoes/_form.html.erb
<%= form_for(@shoe) do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.collection_select(:company_id, Company.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>Editing shoe</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<%= render 'common/shoe_list' , shoes: @shoes, most_viewed: @most_viewed%>

app/views/shoes/new.html.erb
<h1>New shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shoe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @shoe.company.try(:name) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @shoe.category.try(:name) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shoe.price %> $ 
</p>

<p>
  <strong>Image:</strong></br>
  <img src= <%= @shoe.image_url %> height=250 width=250 />
</p>
<h3><i>Comments</i></h3>

<% @all_comments.each do |comment| %>
  <% unless comment.new_record? %>
  <ul>
    <li><i><%= comment.user.try(:email) %></i> : <%= comment.comment %></li>
  </ul>
  <% end %>
<% end %>

<%= form_for(@create_comment) do |f| %>
  <%= f.text_area :comment%>
  <%= f.hidden_field :commentable_id %>
  <%= f.hidden_field :commentable_type %>
  </br>
  <%= f.submit %>
<% end %>
</br>
<%= form_tag send_mail_path(@shoe),method: :get do %>
  <%= label_tag 'Share this shoes to your friends : '%>
  <%= text_field_tag :email %>
  <%= submit_tag 'Send'%>
<% end %>

</br>
<% if current_user.admin? %>
<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<% end %>
<%= link_to 'Back', shoes_path %>