config/routes.rb
Rails.application.routes.draw do
  
  get 'shoes/:id/send_mail' => 'shoes#send_mail', as: :send_mail

  devise_for :admins
  devise_for :users
  
  resources :comments

  resources :categories

  resources :companies

  resources :shoes
  root to: 'shoes#index'

end

app/views/common/_shoe_list.html.erb
<h1>Listing shoes</h1>
<h3>Most View</h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th>Company</th>
      <th>View</th>
    </tr> 
  </thead>

  <tbody>
    <% most_viewed.each do |viewed| %>
    <tr>
      <td><%= viewed.name %></td>
      <td><%= viewed.price %>$</td>
      <td><%= viewed.company.name %></td>
      <td><%= viewed.category.name %></td>
      <td><%= viewed.impressionist_count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h3>All Shoes</h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Company</th>
      <th>Category</th>
      <th>Image</th>
      <th>Views</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% shoes.each do |shoe| %>
      <tr>
        <td><%= shoe.name %></td>
        <td><%= shoe.description %></td>
        <td><%= shoe.price %>$</td>
        <td><%= shoe.company.try(:name) %></td>
        <td><%= shoe.category.try(:name) %></td>
        <td><img src=<%= shoe.image_url %> height=50 width=50 /></td>
        <td><%= shoe.impressionist_count %></td>
        <td><%= link_to 'Show', shoe %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_shoe_path(shoe) %></td>
        <td><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if current_user.admin? %>
<%= link_to 'New Shoe', new_shoe_path %>
<% end %>
<%= will_paginate shoes %>