config/routes.rb
Rails.application.routes.draw do
  
  get 'shoes/:id/send_mail' => 'shoes#send_mail', as: :send_mail

  devise_for :admins
  devise_for :users
  
  resources :comments

  resources :categories

  resources :companies

  resources :shoes
  root to: 'shoes#index'

end

app/views/layouts/_footer.html.erb
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"><a href="http://www.templatesfreelance.com/"><img src=<%= asset_path "footer.gif"%> alt="" width="920" height="4" border="0"></a></td>
  </tr>
  <tr>
    <td height="60" align="center"><a href="http://www.templatesfreelance.com/">Home</a> | <a href="http://www.templatesfreelance.com/">News</a> | <a href="http://www.templatesfreelance.com/">Reviews</a> | <a href="http://www.templatesfreelance.com/">How-To's</a> | <a href="http://www.templatesfreelance.com/">Downloads</a> | <a href="http://www.templatesfreelance.com/">Shop &amp; Compare</a> | <a href="http://www.templatesfreelance.com/">Apps</a> | <a href="http://www.templatesfreelance.com/">Business Center</a> | <a href="http://www.templatesfreelance.com/">FAQ</a> | <a href="http://www.templatesfreelance.com/">Contact Us</a><br>
    TemplatesFreeLance.com &copy; copyright 2012 - <a href="http://www.templatesfreelance.com/">Web Page Templates </a></td>
  </tr>

app/views/layouts/_sidebar.html.erb
<td width="192" height="479"><table width="192"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td height="38" class="topMenu LeftMenuHeader" >Categories</td>
          </tr>
        </table>          
          <table width="100%"  border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="216" valign="top">
                <div class="RightMenu">
                  <ul>

                    <ul><h3><%= link_to "All Companies", companies_path %></h3>
                    <% companies.each do |t| %>
                      <li><a href=<%= company_path(t) %> ><%= t.name %></a></li>
                    <% end %>
                    </ul>
                    
                    
                    <ul><h3><%= link_to "All Categories", categories_path %></h3>
                    <% categories.each do |u| %>                                        
                      <li><a href=<%= category_path(u) %> ><%= u.name %></a></li>
                    <% end %>
                    </ul>                   
                    
                  </ul>
              </div></td>
            </tr>
          </table>
          <table width="100%"  border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><a href="http://www.templatesfreelance.com/"><img src=<%= asset_path "rightBaner.jpg"%> alt="" width="192" height="334" border="0"></a></td>
            </tr>
          </table></td>

app/views/layouts/_top.html.erb
<tr>
    <td height="25">&nbsp;</td>
  </tr>
  <tr>
    <td height="77" class="header"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="28%" align="left"><a href="http://www.templatesfreelance.com/"><img src=<%= asset_path "logo.jpg"%> alt="" width="262" height="77" border="0"></a></td>
        <td width="72%" align="right">
		<% if user_signed_in? %>
			<b>Welcome:</b> 
			<i><%= current_user.email %></i>
			<%= link_to "Sign Out", destroy_user_session_path , method: :delete %>
		<% else %>
			<%= link_to "Sign Up",new_user_registration_path %>
			<%= link_to "Sign In",new_user_session_path %>
		<% end %>
		</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td height="38" class="menu">
	
	<div class="menuLs">
				<ul>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Home</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">News</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Reviews</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">How-To's </a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Downloads</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Shop & Compare</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Apps</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Business Center</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">FAQ</a></li>
				</ul>
	</div>	</td>
  </tr>
  <tr>
    <td height="20">&nbsp;</td>
  </tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoeStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<table width="920"  border="0" cellspacing="0" cellpadding="0" align="center">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>  
  <%= render 'layouts/top'%>

  <tr>
    <td><table width="920"  border="0" cellspacing="0" cellpadding="0">
      <tr align="left" valign="top">
        
        <%=render 'layouts/sidebar',companies: @companies,categories: @categories%>

        <td width="727">
		
		    <%= render 'layouts/main'%>  
		    <%= yield %>
		  </td>
      </tr>
    </table></td>
  </tr>
  
  <%= render 'layouts/footer'%>
</table>
</body>

</html>